### ISSUE TITLE
IBM Database

### ISSUE THREAD

**Issue by AnnaZHoner** [AnnaZHoner/SWENG#8]

**Comment by AnnaZHoner** [comment]
Create the one database to cover country listing etc from plugin and twitter data. (Cloudant)

**Comment by smokett** [comment]
I put data into the database, but don't know how to get them in the plugin. I tried to directly call a http request, I can successfully do this in browser, but can't do this in the plugin, it always gave me a 401 unauthorized error. I also tried to set the permissions for my database, but it always said I either supplied the wrong credentials or browser doesn't understand how to supply the credentials required. But I did this in terminal and here's no place to enter password(I tried to add password, but then the system told me that I sent a unknown request)

**Comment by smokett** [comment]
Done this. Now the countries and cities data are on IBM cloudant database.
